### ISSUE TITLE
Cannot build IDS Connector

### ISSUE THREAD

**Issue by treufuss** [gyroidos/gyroidos_build#13] opened 2019-01-09 12:35 UTC
Hello there,

I tried building trustme as the IDS Connector and followed [this documentation](https://industrial-data-space.github.io/trusted-connector-documentation/docs/dev_trustme/), using the docker environment. 

The execution of "make ids-all" got abrupted at the following command
`cd external/trusted-connector && mvn clean install -DskipITs -DskipTests -DskipDocker`
because the `mvn` command was not found. So I installed maven within the docker container manually, but then it got stuck at the same place because there is no POM within the directory.

Any suggestions how to fix this and getting trustme up and running?

Thanks.

**Comment by quitschbo** [comment] 2019-01-09 16:10
Hi treufuss,

it seems that the guys who maintain the trusted-connector changed their build
system. I will take a look into that.
However, we are currently in the process to switch the underlying android system to yocto
for the ids stuff. I think in the next weeks or so, we will provide a new/updated how-to for doing
an integrated build with the trusted-connector as core container in the new yocto-based trustme
System.

Cheers,
quitschbo

**Comment by quitschbo** [comment] 2019-01-21 12:59
Hi treufuss,

the Android build should work again if you use the trustme-7.1.2_r33-github branch
as described in: https://github.com/trustm3/trustme_build/blob/trustme-7.1.2_r33-github/doc/ids-README.md
I also updated the Dockerfile, thus the Docker build should work, too.

However, it seems there is a problem with the upstream trusted-connector code and the
current trustme platform. In my tests, the web-console of the IDS Connector did not show up.

However, I could connect to the karaf console by:
`pid=$(ps | grep cml-service-container)`
`cml-run ${pid} /root/bin/client`

We will consider this in the upcoming yocto based build.

Cheers,
quitschbo

**Comment by treufuss** [comment] 2019-01-23 09:56
Hey, thanks for the update. Unfortunately the build still doesn't run through for me. See the following log: 
[idsBuildLog.txt](https://github.com/trustm3/trustme_build/files/2786629/idsBuildLog.txt)

**Comment by quitschbo** [comment] 2019-01-25 17:53
The branch for the cml repository in the manifest was wrong.
I have pushed a fix.
Just do a `repo sync` and try to build again.

**Comment by ntchristos** [comment] 2019-02-13 11:33
Hello,
i also have problems with the build. I think i followed the instructions correctly. See the following log:
[log.txt](https://github.com/trustm3/trustme_build/files/2860080/log.txt)

**Comment by quitschbo** [comment] 2019-02-19 16:06
Hi, looks like that you don't have the m4 tool installed in your host distribution.
`apt-get install m4`

However, I would recommend to build with the yocto tool chain using Docker.
https://github.com/trustm3/trustme_build/blob/master/yocto/docker/README.md

After that you can use kvm/qemu to start the base system:
https://github.com/trustm3/trustme_build/tree/master/yocto#run-trustme-image-in-qemukvm-x86-64

**Comment by nalexopo** [comment] 2019-02-22 09:14
I am also trying to run this without luck. I am totally unfamiliar with yocto. Does it build as is with the directions you give or do I have to poke around yocto files? Because if I run it as is I run into errors. 

Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
root@6189cc2d40dd:/opt/ws-yocto/poky/build# bitbake trustx-cml-initramfs multiconfig:container:ids
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 2 entries from dependency cache.
ERROR: /opt/ws-yocto/poky/meta/recipes-support/vte/vte_0.48.3.bb: Unable to determine endianness for architecture 'INVALID'
ERROR: /opt/ws-yocto/poky/meta/recipes-support/vte/vte_0.48.3.bb: Please add your architecture to siteinfo.bbclass
ERROR: Failed to parse recipe: /opt/ws-yocto/poky/meta/recipes-support/vte/vte_0.48.3.bb

**Comment by quitschbo** [comment] 2019-02-25 09:38
If you run inside the provided Docker environment, it should work out of the box. But maybe there has something changed upstream.
Could you try to set the Machine in out-yocto/conf/multiconfig/container.conf
`MACHINE = "trustx-corei7-64" `
and run 
`bitbake trustx-cml-initramfs multiconfig:container:ids`
again

**Comment by nalexopo** [comment] 2019-02-25 12:53
Sorry I forgot that I had disabled the sanity checker to see what happens. So problem starts with previous command:
source init_ws.sh out-yocto

I attach logs:
[log.txt](https://github.com/trustm3/trustme_build/files/2900584/log.txt)

**Comment by quitschbo** [comment] 2019-02-26 07:29
do you use the provided script `run-docker.sh` to run docker?
If so, your local user of your host machine should be mapped to the docker container.
The log says that you are root.
- So either you have started docker as root, then start it as normal user.
- Or maybe your docker/kernel does not support this feature of docker.
How old is your host-machines distro/kernel?

**Comment by nalexopo** [comment] 2019-02-26 11:15
It was the first bullet indeed. Thank you!

Now it gets stuck on the bitbake command. Producing the attached log. 

Are there any minimum specs ??? I run the minimum specs of this guide in a VM
[https://industrial-data-space.github.io/trusted-connector-documentation/](url) 

My kernel end OS are these:
Operating System: Ubuntu 18.04.2 LTS
Kernel: Linux 4.15.0-45-generic
Architecture: x86-64

[log.txt](https://github.com/trustm3/trustme_build/files/2905096/log.txt)

**Comment by quitschbo** [comment] 2019-02-26 11:58
No this seems fine, the rest should be handled in the Docker builder.
Did you try the proposed change to out-yocto/conf/multiconfig/container.conf ?

**Comment by quitschbo** [comment] 2019-02-26 12:06
Ah I thought the log would be the same as above, sorry.
It seems that you ran out of memory during build.
The requirements there are for running the trusted connector not for building the core platform.
have a look at your disk space.
my source and buildout in total is about 70-80 GB

**Comment by nalexopo** [comment] 2019-02-26 12:12
I have 130 GB free before build. But I am afraid I can't give more in this computer.

**Comment by quitschbo** [comment] 2019-02-26 12:22
so 130 GB should be enough, maybe than its your RAM which is the problem.

You could also limit parallelism in out-yocto/conf/local.conf

> \# Uncomment and set to allow bitbake to execute multiple tasks at once.
> \# For a quadcore, BB_NUMBER_THREADS = "4", PARALLEL_MAKE = "-j 4" would
> \# be appropriate.
> \# BB_NUMBER_THREADS = "4"
> \# Also, make can be passed flags so it run parallel threads e.g.:
> \# PARALLEL_MAKE = "-j 4"

**Comment by nalexopo** [comment] 2019-02-27 12:09
After maxing the vm RAM these are the errors i encountered.

ERROR: trustx-cml-initramfs-1.0-r0 do_rootfs: Function failed: sign_modules (log file is located at /opt/ws-yocto/out-yocto/tmp/work/trustx_corei7_64-poky-linux-musl/trustx-cml-initramfs/1.0-r0/temp/log.do_rootfs.3299)
ERROR: Logfile of failure stored in: /opt/ws-yocto/out-yocto/tmp/work/trustx_corei7_64-poky-linux-musl/trustx-cml-initramfs/1.0-r0/temp/log.do_rootfs.3299
ERROR: Task (/opt/ws-yocto/meta-trustx/images/trustx-cml-initramfs.bb:do_rootfs) failed with exit code '1'

**Comment by quitschbo** [comment] 2019-02-28 07:55
can you dump the logfile?
/opt/ws-yocto/out-yocto/tmp/work/trustx_corei7_64-poky-linux-musl/trustx-cml-initramfs/1.0-r0/temp/log.do_rootfs.3299

**Comment by nalexopo** [comment] 2019-02-28 08:43
Here it is

[log.txt](https://github.com/trustm3/trustme_build/files/2914101/log_do_rootfs.txt)

**Comment by quitschbo** [comment] 2019-03-01 13:48
seems that you have some undefined state of your work dir, due to previous failed build attempts.
You can try to clean the kernel target and run the image build again:
`bitbake -ccleansstate virtual/kernel`
`bitbake trustx-cml-initramfs`
That worked for me if I manually reproduce your error by deleting that missing file in your log.txt:
/opt/ws-yocto/out-yocto/tmp/work-shared/trustx-corei7-64/kernel-build-artifacts/sign-file

otherwise I would recommend to delete the out-yocto directory and restart from scratch

**Comment by nalexopo** [comment] 2019-03-07 08:45
Hello,

Bitbake command produces these errors on Terminal


WARNING: mc:container:libpng-native-1.6.31-r0 do_fetch: Failed to fetch URL http://downloads.sourceforge.net/project/libpng/libpng16/1.6.31/libpng-1.6.31.tar.xz, attempting MIRRORS if available
WARNING: mc:container:coreutils-8.27-r0 do_fetch: Failed to fetch URL http://distfiles.gentoo.org/distfiles/coreutils-8.27-man.tar.xz;name=manpages, attempting MIRRORS if available
ERROR: mc:container:cmld-git+AUTOINC+2f18e7e7f2-r0 do_compile: oe_runmake failed
ERROR: mc:container:cmld-git+AUTOINC+2f18e7e7f2-r0 do_compile: Function failed: do_compile (log file is located at /opt/ws-yocto/out-yocto/tmp_container/work/corei7-64-poky-linux/cmld/git+AUTOINC+2f18e7e7f2-r0/temp/log.do_compile.18787)
ERROR: Logfile of failure stored in: /opt/ws-yocto/out-yocto/tmp_container/work/corei7-64-poky-linux/cmld/git+AUTOINC+2f18e7e7f2-r0/temp/log.do_compile.18787
ERROR: Task (multiconfig:container:/opt/ws-yocto/meta-trustx/recipes-trustx/cmld/cmld_git.bb:do_compile) failed with exit code '1'


And these are the logs mentioned on above errors

[logdocompile18787.txt](https://github.com/trustm3/trustme_build/files/2940252/logdocompile18787.txt)

**Comment by quitschbo** [comment] 2019-03-08 07:25
yeah we accidentally merged a patch in the cml repository the last days, the fix
is already merged now.
Just update the cml repository in your work dir:
`cd  /opt/ws-yocto/trustme/cml`
`repo sync .`

and build again.

**Comment by nalexopo** [comment] 2019-03-21 13:05
Hello,

I think I have managed to build. I can see 
trustmeimage-201903191234-sda.direct in /home/nalexopo/ws-yocto/out-yocto
and
containers.btrfs in /home/nalexopo/ws-yocto/out-yocto

However, I must note that after doing repo sync in cml, it didn't work right away but I did a few bitbake cleans (bitbake -ccleansstate virtual/kernel) and tried again.

Above command:

 kvm -m 4096 -bios OVMF.fd -serial mon:stdio -device virtio-scsi-pci,id=scsi -device scsi-hd,drive=hd0 -drive if=none,id=hd0,file=$(ls trustmeimage-* | tail -n1),format=raw -device scsi-hd,drive=hd1 -drive if=none,id=hd1,file=containers.btrfs,format=raw

Outputs:
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory

Thank you,

 I did some research and this command:
dmesg | grep kvm

returns me
[    0.000000] kvm-clock: cpu 0, msr 1:1ff50001, primary cpu clock
[    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
[    0.000000] kvm-clock: using sched offset of 14189651488 cycles
[    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.004000] kvm-clock: cpu 1, msr 1:1ff50041, secondary cpu clock
[    0.135052] clocksource: Switched to clocksource kvm-clock
[ 8772.514847] kvm: no hardware support


Also running this command:
/usr/sbin/kvm-ok
Outputs this:
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used

I can see VT-x in BIOS ENABLED and I have it ENABLED from virtual box however I get the above.

I

**Comment by quitschbo** [comment] 2019-03-23 06:35
From what your saying it looks like you do not use KVM natively on your machine.
Look for **nested** virtualization KVM virtulbox or what ever virtualization setup you have beneath.
Or just take the image to a machine which runs Linux/KVM natively,
Otherwise you can stick to emulation and run qemu instead of the kvm command,
however this is slow.

**Comment by nalexopo** [comment] 2019-03-28 11:07
I got it running today on a pc with native linux. I have a qemu console running. one window is stuck saying "Waiting for tpm2d's control interface", when I switch terminal the keyboard doesn't give input. So I don't know how to proceed. 

What I want to do is to read some sensor data and relay them to another pc. I have a backend for this written in python I just want to do it through IDS. Is there some comprehensive guide on how to integrate your code into ids?

**Comment by k0ch4lo** [comment] 2019-04-03 15:59
Hi nalexopo,
it's good to hear the build now worked.
yesterday we pushed a fix for the tmp2d issue. Please do a repo sync and build again to see if the issue is solved.

Also, we are currently writing some documentation on how to build and operate trustme.
It is currently work in progress and not yet officially supported, but if you find it useful you can use the current version at [trustm3.github.io/documentation](https://trustm3.github.io/documentation/)

**Closed as completed** 2019-07-26 14:47 UTC
